routes/web.php
<?php

Auth::routes(['verify' => 'true']);

Route::get('/', 'ViewController@welcome')->name('view.welcome');

Route::resource('posts', 'Client\PostController')->only(['index', 'show']);

Route::resource('categories', 'Client\CategoryController')->only(['index', 'show']);

Route::get('profile/{user}', 'Client\ProfileController@index')->name('profile.show');

Route::post('/search', 'HomeController@search')->name('search');

Route::get('/home', 'HomeController@index');

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'verified', 'auth'], function(){
		Route::get('{user}/profile/changepicture', 'Auth\PictureChangeController@index')->name('change.picture.edit');

		Route::post('{user}/profile/changepicture', 'Auth\PictureChangeController@update')->name('change.picture.update');	

		Route::get('{user}/profile/changepassword', 'Auth\PasswordChangeController@index')->name('change.password.edit');

		Route::post('{user}/profile/changepassword', 'Auth\PasswordChangeController@store')->name('change.password.update');
		
		Route::get('{user}/profile/changeusername', 'Auth\UsernameChangeController@edit')->name('change.username.edit');
		
		Route::patch('{user}/profile/changeusername', 'Auth\UsernameChangeController@update')->name('change.username.update');

		Route::resource('/', 'UsersController');
		
		Route::get('profile/{user}/edit', 'UsersController@profile')->name('profile.edit');
		Route::resource('posts', 'PostController')->except(['index', 'show']);
		Route::resource('categories', 'CategoryController')->except(['index', 'show']);
		Route::resource('comments', 'CommentController');
	});
});

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'auth'], function() {
		Route::get('profile/{user}', 'UsersController@index')->name('profile.show');
		
		Route::resource('posts', 'PostController')->only(['index', 'show']);
		Route::resource('categories', 'CategoryController')->only(['index', 'show']);
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Post;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * relationship between Post and user
     * 
     * @return [type] [description]
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    
    public function getRouteKeyName()
    {
        return 'name';
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Post;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserUpdateRequest;

class UsersController extends Controller
{
    public function profile(User $user)
    {
        if(!$this->authUser($user)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('warning', 'Unauthorize action.');
        }

        return view('users.index', compact('user'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $posts = $user->posts()->latest()->paginate(20);
        return view('users.show', compact('user', 'posts'));
    } 

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        // $posts = Post::where('user_id', $user->id)->paginate(20);
        // return view('users.show', compact('user', 'posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(!$this->authUser($user)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('warning', 'Unauthorize action.');
        }
        return view('users.edit.imagechange', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        if(!$this->authUser($user)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('warning', 'Unauthorize action.');
        }

        $user->update($request->all());

        if($request->hasFile('avatar')) {
            $directory = 'images';
            $imageName = time().'.'.$request->avatar->extension();
            $request->avatar->move($directory, $imageName);
            $user->avatar = $directory . '/' . $imageName;
        }

        $user->save();

        return redirect()->route('users.show', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     *
     * 
     * @param  [type] $user [description]
     * @return [type]       [description]
     */
    public function authUser($user) 
    {
        return $user->id == Auth::id();
    }


}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('head')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

@section('content')

@if($errors->any())
    <div class="alert alert-danger">
        <strong>Opps!</strong> There were some problems with your input.<br><br>
            <button type="button" class="close" data-dismiss="alert">×</button>	
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('users.update', $user) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PATCH')
            <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>User Name</strong>
                        <input type="text" name="title" class="form-control" value="{{ $user->name }}">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Image</strong>
                        <input type="file" name="avatar" class="form-control">
                    </div>
                </div>

                
   
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
   
            </div>
</form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <div class="flex">
                <a class="mx-auto" href="{{ route('profile.show', $user) }}">
                    <img class="rounded-full" src="{{ asset('/'. $user->avatar  ) }}" style="height: 50px; width: 50px;"/>
                </a>
            </div>
            <div class="flex mt-3">
                <a class="mx-auto" href="{{ route('profile.show', $user) }}">
                    <span class="font-bold text-xl mx-auto">{{$user->name}}</span>
                </a>
            </div>
            <div class="flex mt-4">
                <a href="{{ route('user.change.picture.edit', $user) }}" class="w-full text-center py-3 md:w-sm bg-blue-800 mx-auto text-white font-bold px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded" type="submit">
                    Change Profile Picture
                </a>
            </div>
            <div class="flex mt-4">
                <a href="{{ route('user.change.password.edit', $user) }}" class="w-full text-center py-3 md:w-sm bg-blue-800 mx-auto text-white font-bold px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded" type="submit">
                Change Password
                </a>
            </div>
            <div class="flex mt-4">
                <a href="{{ route('user.change.username.edit', $user) }}" class="w-full text-center py-3 md:w-sm bg-blue-800 mx-auto text-white font-bold px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded" type="submit">
                Change Username
                </a>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')

<div class="container mx-auto">
	<div class="rounded mx-auto bg-white rounded-t-lg overflow-hidden shadow max-w-xs my-3 ">
		<img src="https://i.imgur.com/dYcYQ7E.png" class="w-full"/>
		<div class="flex justify-center -mt-8">
		<a href="">
			<img src="{{ asset('/'. $user->avatar  ) }}" style="height: 50px; width: 50px;" class="rounded-full border-solid border-white border-2 -mt-3">
		</a>		
		</div>
		<div class="text-center px-3 pb-6 pt-2">
			<h3 class="text-black text-sm bold font-sans">{{ $user->name }}</h3>
			<p class="mt-2 font-sans font-light text-grey-dark">Hello, i'm developer!</p>
		</div>
		<div class="flex justify-center pb-3 text-grey-dark">
		<div class="text-center mr-3 pr-3">
			<h2>{{ $user->posts->count() }}</h2>
			<span>Posts</span>
		</div>
		</div>
	</div>

	<div class="flex p-2">
        <h1 class="text-xl mx-auto">All Posts By <strong>{{ $user->name }}</strong></h1>
    </div>
    
</div>

<!-- cards -->
<div class="container my-2 mx-auto px-4 md:px-12">
    <div class="flex flex-wrap -mx-1 lg:-mx-4">   
        @foreach($posts as $post)
  
        <div class="my-4 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
                <div class="w-full max-w-sm overflow-hidden rounded border bg-white hover:shadow-xl mx-auto">
                    <div class="relative">
                        <a href="{{ route('user.posts.show', $post) }}">    
                            <img class="w-full object-fill h-40" src="{{ ('/'. $post->cover) }}">
                        </a>
                    <div style="bottom: -20px;" class="absolute right-0 w-10 mr-2">
                        <a href="{{ route('user.profile.show', $post->user) }}">
                        <img class="rounded-full border-2 border-white" style="height: 40px; width: 40px;" src="{{ asset('/'. $post->user->avatar) }}" >
                        </a>
                    </div>
                    </div>
                    <div class="p-3">
                    <h3 class="mr-10 text-sm truncate-2nd">
                        <a class="hover:text-blue-500" href="{{ route('user.posts.show', $post) }}">{{ Str::limit($post->title, 30) }}</a>
                    </h3>
                    <div class="flex items-start justify-between">
                        <p class="text-xs text-gray-500">{{ Str::limit($post->short_des, 35) }}</p>
                    </div>
                    <p class="text-xs text-gray-500"><a href="{{ route('user.profile.show', $post->user) }}" class="hover:underline hover:text-blue-500">{{ $post->user->name }}</a> • {{ $post->created_at->diffForHumans() }}</p>
                    </div>
                </div>
            </div>
        
        @endforeach
    </div>
</div>
@endsection