routes/web.php
<?php

Auth::routes(['verify' => 'true']);

Route::get('/', 'ViewController@welcome')->name('view.welcome');

Route::resource('posts', 'Client\PostController')->only(['index', 'show']);

Route::resource('categories', 'Client\CategoryController')->only(['index', 'show']);

Route::get('profile/{user}', 'Client\ProfileController@index')->name('profile.show');

Route::post('/search', 'HomeController@search')->name('search');

Route::get('/home', 'HomeController@index');

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'verified', 'auth'], function(){
		Route::get('{user}/profile/changepicture', 'Auth\PictureChangeController@index')->name('change.picture.edit');

		Route::post('{user}/profile/changepicture', 'Auth\PictureChangeController@update')->name('change.picture.update');	

		Route::get('{user}/profile/changepassword', 'Auth\PasswordChangeController@index')->name('change.password.edit');

		Route::post('{user}/profile/changepassword', 'Auth\PasswordChangeController@store')->name('change.password.update');
		
		Route::get('{user}/profile/changeusername', 'Auth\UsernameChangeController@edit')->name('change.username.edit');
		
		Route::patch('{user}/profile/changeusername', 'Auth\UsernameChangeController@update')->name('change.username.update');

		Route::resource('/', 'UsersController');
		
		Route::get('profile/{user}/edit', 'UsersController@profile')->name('profile.edit');
		Route::resource('posts', 'PostController')->except(['index', 'show']);
		Route::resource('categories', 'CategoryController')->except(['index', 'show']);
		Route::resource('comments', 'CommentController');
	});
});

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'auth'], function() {
		Route::get('profile/{user}', 'UsersController@index')->name('profile.show');
		
		Route::resource('posts', 'PostController')->only(['index', 'show']);
		Route::resource('categories', 'CategoryController')->only(['index', 'show']);
	});
});

app/Post.php
<?php

namespace App;

use App\User;
use App\Comment;
use App\Category;
use Illuminate\Support\Str;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;
use Illuminate\Database\Eloquent\Model;

class Post extends Model implements Searchable
{
    protected $guarded =[];

    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id');
    }
    /**
     *
     * 
     */
    public function setSlugAttribute($value) {

    if (static::whereSlug($slug = Str::slug($value))->exists()) {

        $slug = $this->incrementSlug($slug);
    }

        $this->attributes['slug'] = $slug;
    }

    public function incrementSlug($slug) {

    $original = $slug;

    $count = 2;

    while (static::whereSlug($slug)->exists()) {

        $slug = "{$original}-" . $count++;
    }

        return $slug;

    }

    /**
     *eloquent relation for user and post
     * 
     * @return [type] [description]
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     *eloquent releation for category and post
     * 
     * @return [type] [description]
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * use post url slug
     * 
     * @return [type] [description]
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * use in search result
     * 
     * @return [type] [description]
     */
    public function getSearchResult(): SearchResult
    {
        $url = route('posts.show', $this->slug);

        return new SearchResult(
            $this,
            $this->title,
            $url
        );
    }
}

app/Http/Controllers/Client/PostController.php
<?php

namespace App\Http\Controllers\Client;

use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('client.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Post;
use Purifier;
use App\Category;
use App\Comment;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\PostStoreRequest;
use App\Http\Requests\PostUpdateRequest;


class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        // $posts = Post::where('user_id', '=', Auth::id())->paginate(20);
        $posts = auth()->user()->posts()->paginate(20);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostStoreRequest $request)
    {
        $imageName = time().'.'.$request->cover->extension();  
        $directory = 'images';

        $data = [
            'title' => request('title'),
            'short_des' => request('short_des'),
            'body' => Purifier::clean(request('body')),
            'user_id' => auth()->id(),
            'slug' => Str::slug($request->title, '-'),
            'category_id' => request('category_id'),
            'cover' => $directory. '/' . $imageName,
        ];
        $request->cover->move($directory, $imageName);

        $post = new Post($data);
        
        
        $post->save();


        return redirect()
                        ->route('user.posts.index')
                        ->with('success', 'A post created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $comments = Comment::where('post_id', $post->id)->latest()->paginate(20);
        
        return view('posts.show', compact('post', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();

        if(!$this->checkAuth($post)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('warning', 'Unauthorize to edit.');
        }

        return view('posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, Post $post)
    {
        if(!$this->checkAuth($post)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('warning', 'Unauthorize to edit.');
        }

        $post->update($request->all());         

        if($request->hasFile('cover')) {
            $directory = 'images';
            $imageName = time().'.'.$request->cover->extension();
            $request->cover->move($directory, $imageName);
            $post->cover = $directory . '/' . $imageName;
        }

        $post->save();

        return redirect()
                        ->route('user.posts.index')
                        ->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if(!$this->checkAuth($post)){
            return redirect()
                    ->route('user.posts.index')
                    ->with('error', 'Unauthorize to delete.');
        }
        $post->delete();
        return redirect()
                        ->route('user.posts.index')
                        ->with('warning', 'A post deleted.');
    }

    public function checkAuth($post)
    {
        return $post->user_id == Auth::id();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('head')
    <script src="{{ asset('node_modules/tinymce/tinymce.js') }}"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

@section('content')

@if($errors->any())
    <div role="alert w-1/4">
    <div class="bg-red-500 w-1/4 text-white font-bold rounded-t px-4 py-2">
        There were problem with your input.
    </div>
    <div class="w-1/4 border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    </div>
@endif
<div class="flex justify-center">
<div class="container p-2 lg:p-16 bg-white lg:w-2/3 w-11/12 rounded-lg">
    <div class="flex mb-8">
        <h1 class="text-black text-3xl font-bold uppercase mx-auto">create new Post</h1>
    </div>
    <form action="{{ route('user.posts.store') }}" method="POST" enctype="multipart/form-data" class="w-full">
                @csrf
                
        <div class="container my-4">
            <strong>Title</strong>
            <input type="text" name="title" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Title">
        </div>
        

        <div class="container my-4">
            <strong>Description</strong>
            <input type="text" name="short_des" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Short description of you're article.">
        </div>

        
        <div class="container my-4">
            <strong>Full Article</strong>
            <textarea name="body" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text">{!! $html ?? '' !!}</textarea>
        </div>
        

        
        <div class="container my-4">
            <strong class="block mb-2">Image:</strong>
            <label class="block text-sm text-gray-700 mb-2">• Acceptable image dimensions are minimum 900x300 and maximum 1250x500.</label>
            <label class="block text-sm text-gray-700">• File size cannot exceed 2 MB.</label> 
            
            <input type="file" name="cover" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
       

        <div class="container my-4">
            <strong>Category</strong>
            <select class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline bg-white" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">
                        {{$category->name}}
                    </option>
                @endforeach
            </select>
	    </div>

        <div class="container my-4 flex justify-between">
            <a href="{{ route('user.posts.index') }}" class="shadow btn btn-blue text-xs md:text-lg">Cancel</a>
            <button type="submit" class="shadow btn btn-blue text-xs md:text-lg">Submit</button>
        </div>
    </form>
</div>
</div>
@endsection

resources/views/posts/delete.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card mb-4">
                <div class="card-header">Confirm Post delete.</div>

                <div class="card-body">
                    <p>Are you sure you'd like to delete <strong>{{ $post->title }}</strong>?</p>

                    <form action="{{ route('user.posts.destroy', $post) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Yes, delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('head')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

@section('content')

@if($errors->any())
    <div class="alert alert-danger">
        <strong>Opps!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="flex justify-center">
<div class="container p-2 lg:p-16 bg-white lg:w-2/3 w-11/12 rounded-lg">
    <div class="flex mb-8">
        <h1 class="text-black text-3xl font-bold uppercase mx-auto">Edit Post</h1>
    </div>
    <form action="{{ route('user.posts.update', $post) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
        <div class="container my-4">
            <strong>Title</strong>
            <input type="text" name="title" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Title" value="{{ $post->title }}">
        </div>
        

        <div class="container my-4">
            <strong>Description</strong>
            <input type="text" name="short_des" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ $post->short_des }}">
        </div>

        
        <div class="container my-4">
            <strong>Full Article</strong>
            <textarea name="body" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text">{{ clean($post->body) }}</textarea>
        </div>

        <div class="container my-4">
            <strong class="block mb-2">Image:</strong>
            <label class="block text-sm text-gray-700 mb-2">• Acceptable image dimensions are minimum 900x300 and maximum 1250x500.</label>
            <label class="block text-sm text-gray-700">• File size cannot exceed 2 MB.</label> 
            
            <input type="file" name="cover" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
       

        <div class="container my-4">
            <label>Category</label>
            <select class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline bg-white" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">
                        {{$category->name}}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="container my-4 flex justify-between">
            <a href="{{ route('user.posts.index') }}" class="btn btn-blue text-xs md:text-lg">Cancel</a>
            <button type="submit" class="btn btn-blue text-xs md:text-lg">Submit</button>
        </div>
    </form>
</div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')


@section('content')
@if($errors->any())
    <div class="bg-red-500">
        <button type="button" class="close" data-dismiss="alert"></button>	
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif    
@if($posts->count())

<div class="container bg-white mx-auto md:w-4/5 lg:w-3/4 xl:w-2/3 py-8">
    <div class="flex justify-end px-4 mb-4">
        <a href="{{ route('user.posts.create') }}" class="btn btn-blue">NEW POST</a>
    </div>

    <hr>
    @foreach($posts as $post)
    
    <div class="mt-8 mx-4 mb-4">
        <div class="h-24">
            <h3 class="h-8 text-xl font-bold mx-2 my-2">
                <a href="{{ route('user.posts.show', $post) }}">{{ Str::limit($post->title, 20) }}</a>
            </h3>
            <div>
                <h3 class="h-12 mx-2">
                    <a href="{{ route('user.posts.show', $post) }}">{{ Str::limit($post->short_des, 30) }}</a>
                </h3>
            </div>
        </div>
        
        <div class="h-10 mx-2 flex justify-start">
            <a href="{{ route('user.posts.edit', $post) }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">Edit</a>

            <form action="{{route('user.posts.destroy',$post)}}" method="POST">
                @csrf
                @method('DELETE')

            <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4  border-blue-700 rounded mx-2">Delete</button>
            </form>

        </div>
    </div>
    <hr class="my-1">
    @endforeach
</div>

@else
    <div class="container bg-white mx-auto p-4 md:w-2/3">
        <div class="flex justify-end px-4 mb-4">
            <a href="{{ route('user.posts.create') }}" class="btn btn-blue">NEW POST</a>
        </div>
        <p class="text-xl font-bold">You Currently dont have any post. <a href="{{ route('user.posts.create') }}">Click here to post new</a></p>
    </div>
@endif
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('head')
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e1eeef9cf446508"></script>
<script src="{{ asset('node_modules/tinymce/tinymce.js') }}"></script>
<script>tinymce.init({ selector:'textarea' });</script>

@endsection

@section('content')
    @if($errors->any())
    <div class="flex items-center bg-blue-500 w-1/4 text-white text-sm font-bold px-4 py-3" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
            <p><ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul></p>
    </div>
    @endif
    <div class="bg-gray-300 p-2 md:p-4">
        <div class="lg:w-2/3 sm:w-11/12 mx-auto p-4 shadow rounded-lg bg-white">
            <div class="my-3">
                <h2 class="text-xl font-bold uppercase">{{ $post->title }}</h2>
            </div>

            <div class="my-3">
                <a class="mx-auto" href="{{ route('user.posts.show', $post) }}">
                    <img src="{{ asset('/'. $post->cover) }}" alt="" class="object-fill h-auto md:object-cover w-full">
                </a>
            </div>

            <div class="my-3">
                <p class="text-sm lg:text-xl">
                    {!! clean($post->body) !!}
                </p>
            </div>

            <div class="my-8">
                <a href="{{ route('user.profile.show', $post->user) }}">
                    <strong>
                        By {{ $post->user->name }}
                    </strong>
                </a>
                        at {{ $post->created_at->diffForHumans() }}.
            </div>

            <div class="my-3">
                <a href="{{ route('user.profile.show', [$post->user]) }}">
                <img class="rounded-full" style="height: 50px; width: 50px;"  src="{{ asset('/'. $post->user->avatar  ) }}" />
                </a>
            </div>

            <div class="my-4">
                <label>Category:</label>
                @if(Auth::user())
                <a href="{{ route('user.categories.show', $post->category->name) }}" class="btn btn-blue">{{ $post->category->name }}</a>
                @else
                <a href="{{ route('categories.show', $post->category->name) }}" class="btn btn-blue">{{ $post->category->name }}</a>
                @endif
            </div>

            <div class="addthis_inline_share_toolbox my-3">
                
            </div>

            @if(Auth::user())
            <div class="my-8">
                <form action="{{ route('user.comments.store') }}" method="POST">
                    @csrf
                    <div class="container my-4">
                        <strong>Add comments</strong>

                        <textarea name="title" class="shadow appearance-none border mt-2 rounded mb-4 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text">{!! $html ?? '' !!}
                        </textarea>
                    </div>

                    <input type="hidden" name="post_id" value="{{ $post->id }}">

                    <div class="container my-4">
                        <button type="submit" class="btn btn-blue">Comment</button>
                    </div>
                </form>
            </div>
            @endif
            <hr>

            <p class="my-4 mb-4">Comments ({{ $comments->count() }})</p>
            <hr>
            @foreach($comments as $comment)
                <div class="my-4 flex border">
                    <div>
                        <div class="p-2">
                            <div class="border shadow-md w-full">
                                <div class="flex">
                                    <a href="{{ route('user.profile.show', [$post->user]) }}">
                                    <img class="rounded-full" style="height: 50px; width: 50px;"  src="{{ asset('/'. $comment->user->avatar  ) }}" />
                                    </a>
                                </div>
                                <div>
                                    <h1 class="text-lg text-center">{{ $comment->user->name }}</h1>
                                    <p class="text-sm">{{ $comment->created_at->diffForHumans() }}</p>
                                </div>
                            </div>                          
                        </div>
                    </div>
                    <div class="my-4 w-4/5 border">
                        <p>{!! clean($comment->title) !!}</p>
                        @if(Auth::user())
                            @if($comment->commentOwner())
                            <div class="flex right-0 bottom-0">
                                <form action="{{ route('user.comments.destroy', $comment) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit">
                                    <img class="mr-3" style="height: 20px; width: 20px;" src="{{ asset('images/trashcan.png') }}">
                                </button>
                                </form>
                                <a href="{{ route('user.comments.edit', $comment) }}"><img style="height: 20px; width: 20px;" src="{{ asset('images/edit.png') }}"></a>
                            </div>
                            @endif
                            @endif
                    </div>
                </div>
            @endforeach
                
        </div>
</div>
@endsection
 