routes/web.php
<?php

Auth::routes(['verify' => 'true']);

Route::get('/', 'ViewController@welcome')->name('view.welcome');

Route::resource('posts', 'Client\PostController')->only(['index', 'show']);

Route::resource('categories', 'Client\CategoryController')->only(['index', 'show']);

Route::get('profile/{user}', 'Client\ProfileController@index')->name('profile.show');

Route::post('/search', 'HomeController@search')->name('search');

Route::get('/home', 'HomeController@index');

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'verified', 'auth'], function(){
		Route::get('{user}/profile/changepicture', 'Auth\PictureChangeController@index')->name('change.picture.edit');

		Route::post('{user}/profile/changepicture', 'Auth\PictureChangeController@update')->name('change.picture.update');	

		Route::get('{user}/profile/changepassword', 'Auth\PasswordChangeController@index')->name('change.password.edit');

		Route::post('{user}/profile/changepassword', 'Auth\PasswordChangeController@store')->name('change.password.update');
		
		Route::get('{user}/profile/changeusername', 'Auth\UsernameChangeController@edit')->name('change.username.edit');
		
		Route::patch('{user}/profile/changeusername', 'Auth\UsernameChangeController@update')->name('change.username.update');

		Route::resource('/', 'UsersController');
		
		Route::get('profile/{user}/edit', 'UsersController@profile')->name('profile.edit');
		Route::resource('posts', 'PostController')->except(['index', 'show']);
		Route::resource('categories', 'CategoryController')->except(['index', 'show']);
		Route::resource('comments', 'CommentController');
	});
});

Route::prefix('user')->name('user.')->group(function() {
	Route::group(['middleware' => 'auth'], function() {
		Route::get('profile/{user}', 'UsersController@index')->name('profile.show');
		
		Route::resource('posts', 'PostController')->only(['index', 'show']);
		Route::resource('categories', 'CategoryController')->only(['index', 'show']);
	});
});

app/Category.php
<?php

namespace App;

use App\Post;
use Illuminate\Database\Eloquent\Model;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;

class Category extends Model implements Searchable
{
    protected $guarded =[];

    /**
     * eloquent relation for category and post
     * 
     * @return [type] [description]
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     *use in search result
     * 
     * @return [type] [description]
     */
    public function getSearchResult(): SearchResult
    {
        $url = route('categories.show', $this->slug);

        return new SearchResult(
            $this,
            $this->name,
            $url
         );
    }
    /**
     * user category url slug
     * 
     * @return [type] [description]
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * user is category creator
     * 
     * @return [type] [description]
     */
    public function categoryOwner()
    {
        return $this->user_id == auth()->id();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Post;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(20);
        
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check()) {
            return back()
                    ->with('info', 'Please Log in first.');
        }
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $data = [
            'name' => request('name'),
            'user_id' => auth()->id(),
            'slug' => $this->createSlug($request->name),
        ];
        
        $categories = new Category($data);

        $categories->save();
        return redirect()
                        ->route('user.categories.index')
                        ->with('success', 'Category created successfully!');
    }

   
    /**
     * createSlug
     *
     * @param  mixed $name
     * @param  mixed $id
     *
     * @return void
     */
    public function createSlug($name, $id = 0)
    {
       
        $slug = Str::slug($name, '-', '');
        
        $allSlugs = $this->getRelatedSlugs($slug, $id);
        
        if (! $allSlugs->contains('slug', $slug)){
            return $slug;
        }
    
        for ($i = 1; $i <= 10; $i++) {
            $newSlug = $slug.'-'.$i;
            if (! $allSlugs->contains('slug', $newSlug)) {
                return $newSlug;
            }
        }
        throw new \Exception('Can not create a unique slug');
    }

    /**
     * getRelatedSlugs
     *
     * @param  mixed $slug
     * @param  mixed $id
     *
     * @return void
     */
    protected function getRelatedSlugs($slug, $id = 0)
    {
        return Category::select('slug')->where('slug', 'like', $slug.'%')
        ->where('id', '<>', $id)
        ->get();
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */

    public function show(Category $category)
     {
       $posts = $category->posts()->latest()->paginate(20);
       return view('categories.show', compact('posts'));
     }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        if(!$this->checkAuth($category)) {
            return redirect()
                    ->back()
                    ->with('info', 'Unauthorized to edit');
        }

        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        if(!$this->checkAuth($category)) {
            return redirect()
                    ->route('user.categories.index')
                    ->with('info', 'Unauthorized to edit');
        }

        $category->slug = Str::slug($request->name, '-');
        $category->update($request->all());
        return redirect()
                        ->route('user.categories.index')
                        ->with('success', 'Category updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {   
        if(!$this->checkAuth($category)) {
            return back()
                    ->with('danger', 'Unauthorized to delete');
        }

        $category->delete();
        return redirect()
                        ->route('user.categories.index')
                        ->with('info', 'Category Deleted.');
    }


    /**
     * checkAuth
     *
     * @param  mixed $category
     *
     * @return void
     */
    public function checkAuth($category)
    {
        return $category->user_id == auth()->id();
    }
}

app/Http/Controllers/Client/CategoryController.php
<?php

namespace App\Http\Controllers\Client;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(20);
        return view('client.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $posts = $category->posts()->latest()->paginate(20);
        return view('client.categories.show', compact('posts', 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
@if($errors->any())
    <div role="alert w-1/4">
    <div class="bg-red-500 w-1/4 text-white font-bold rounded-t px-4 py-2">
        There were problem with your input.
    </div>
    <div class="w-1/4 border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    </div>
@endif
<div class="flex justify-center">
    <div class="container p-2 lg:p-16 bg-white lg:w-2/3 w-11/12 rounded-lg shadow-xl">
        <div class="flex mb-8 bg-white">
            <h1 class="text-black text-xl font-bold uppercase mx-auto">Create Category</h1>
        </div>
        <form action="{{ route('user.categories.store') }}" method="POST">
        @csrf
            <div class="container my-4">
                <p class="my-auto p-2"><strong>Category:</strong></p>
                <input type="text" name="name" placeholder="enter category name" class="w-full h-10 p-2 border">
            </div>

            <div class="container mt-8 flex justify-between">
                <a href="{{ route('user.categories.index') }}" class="btn btn-blue text-xs md:text-lg">Cancel</a>
                <button type="submit" class="btn btn-blue text-xs md:text-lg">Create</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
@if($errors->any())
    <div role="alert w-1/4">
    <div class="bg-red-500 w-1/4 text-white font-bold rounded-t px-4 py-2">
        There were problem with your input.
    </div>
    <div class="w-1/4 border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    </div>
@endif
    <div class="flex justify-center">
        <div class="container p-2 lg:p-16 bg-white lg:w-2/3 w-11/12 rounded-lg shadow-xl">
            <div class="flex mb-8 bg-white">
                <h1 class="text-black text-xl font-bold uppercase mx-auto">Edit Category</h1>
            </div>
            <form action="{{ route('user.categories.update', $category) }}" method="POST">
            @csrf
            @method('PATCH')
                <div class="container my-4">
                        <strong class="p-2">Category:</strong>
                        <input type="text" name="name" class="w-full h-10 p-2 border" placeholder="category-name" value="{{ $category->name }}">
                </div>
                <div class="flex justify-between mt-8">
                    <a href="{{ route('user.categories.index') }}" class="btn btn-blue text-xs md:text-lg">Cancel</a>
                    <button type="submit" class="btn btn-blue text-xs md:text-lg">Edit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

@if($errors->any())
    <div role="alert w-1/4">
    <div class="bg-red-500 w-1/4 text-white font-bold rounded-t px-4 py-2">
        There were problem with your input.
    </div>
    <div class="w-1/4 border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    </div>
@endif
        <div class="w-11/12 md:w-2/3 lg:w-2/3 xl:w-2/3 md:mx-auto lg:mx-auto xl:mx-auto mx-2">

            <div class="container flex justify-end">
                @if(Auth::user())
                <div class="flex my-4">
                    <a href="{{ route('user.categories.create') }}" class="btn btn-blue">New Category</a>
                </div>
                @endif
            </div>

            <div class="bg-white shadow-md rounded my-6 mx-auto shadow-xl">
            <table class="text-left w-full">
            <thead>
                <tr>
                    <th class="py-4 px-6 font-bold uppercase text-sm text-gray-dark">Name</th>
                    <th class="py-4 px-6 font-bold uppercase text-sm text-gray-dark"></th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr class="hover:bg-green-100">
                        @if(Auth::user())
                            <td class="py-4 px-2 md:px-6"><a class="text-xs md:text-lg btn bg-indigo-500 hover:bg-indigo-700" href="{{ route('user.categories.show', $category) }}">{{ $category->name }}</a></td>
                                @if($category->categoryOwner())
                                    <td class="py-4 px-2 md:px-6"><a href="{{ route('user.categories.edit', $category) }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                                            Edit
                                        </a>
                                    </td>

                                    <td class="py-4 px-2 md:px-6">
                                        <form class="inline sm:inline-block" action="{{ route('user.categories.destroy', $category) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                            <button
                                                class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded" type="submit">
                                                Delete
                                            </button>
                                        </form>      
                                    </td>
                                @endif
                        @else
                            <td class="py-4 px-2 md:px-6"><a class="text-xs md:text-lg btn bg-indigo-500 hover:bg-indigo-700" href="{{ route('categories.show', $category) }}">{{ $category->name }}</a></td>
                        @endif
                    </tr>
                @endforeach
            </tbody>
        </table>
        </div>
    </div>
    
	
        {{ $categories->links() }}
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
@if($errors->any())
    <div class="bg-red-500">
        <button type="button" class="close" data-dismiss="alert"></button>	
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif

<div class="container my-2 mx-auto px-4 md:px-12">
    <div class="flex flex-wrap -mx-1 lg:-mx-4">

        
        @foreach($posts as $post)
  
        <div class="my-4 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
                <div class="w-full max-w-sm overflow-hidden rounded border bg-white hover:shadow-xl mx-auto">
                    <div class="relative">
                        <a href="{{ route('user.posts.show', $post) }}">    
                            <img class="w-full object-fill h-40" src="{{ ('/'. $post->cover) }}">
                        </a>
                    <div style="bottom: -20px;" class="absolute right-0 w-10 mr-2">
                        <a href="{{ route('user.profile.show', $post->user) }}">
                        <img class="rounded-full border-2 border-white" style="height: 40px; width: 40px;" src="{{ asset('/'. $post->user->avatar) }}" >
                        </a>
                    </div>
                    </div>
                    <div class="p-3">
                    <h3 class="mr-10 text-sm truncate-2nd">
                        <a class="hover:text-blue-500" href="{{ route('user.posts.show', $post) }}">{{ Str::limit($post->title, 30) }}</a>
                    </h3>
                    <div class="flex items-start justify-between">
                        <p class="text-xs text-gray-500">{{ Str::limit($post->short_des, 35) }}</p>
                    </div>
                    <p class="text-xs text-gray-500"><a href="{{ route('user.profile.show', $post->user) }}" class="hover:underline hover:text-blue-500">{{ $post->user->name }}</a> • {{ $post->created_at->diffForHumans() }}</p>
                    </div>
                </div>
            </div>
        
        @endforeach
    </div>
    </div>
    {{ $posts->links() }}
@endsection